### ISSUE TITLE
Where to find my AUTH0_CERT?

### ISSUE THREAD

**Issue by leonardobilhalva** [unbtbl/Auth0Kit#2]
Hello. U doing good there?

I`m trying to deploy a new vapor server-side system with Auth0Kit package and I`m facing some problems.
I don`t know where to find my AUTH0_CERT or AUTH0_CERT_PATH.

If my API was created using the HS256 protocol, AUTH0_SECRET would be my "Client Secret." Since it was made with RS256, I need to know where to find the AUTH0_CERT.

I`ve found some answers on the internet saying to use https://\(AUTH0_ISSUER)/.well-known/jwks.json to find the jwks, but I don`t know which part of this json answer is the cert key.

**Comment by StefanPrintezis** [comment]
It's a bit late but i'll try and answer for future readers too

### Auth0 Signing Algorithms
HS256 uses a shared secret key (symmetric) for both signing and verifying the token. RS256 uses a private key for signing and a public key for verifying (**a**symmetric).

* HS256 (symmetric): You must securely share the secret between the issuer and any validator. The shared secret can be filled in **AUTH0_SECRET**. This is simpler but can be risky if multiple services need the secret. 
* RS256 (**a**symmetric): Auth0 provides a JWKS endpoint that exposes the public key, so you only need the private key on Auth0’s side. Validators just fetch and cache the public key to verify. This is more secure and is the recommended approach. **AUTH0_CERT** or **AUTH0_CERT_PATH** need to be filled with the public key that begins with '-----BEGIN PUBLIC KEY-----...'. Currently you're able to find the public key under the advanced settings of your application in auth0. **x5c** is generally the property to look for since it contains the base64-encoded x509 public key(s) that can be used to verify your token.

Auth0 has one of the best docs out there, i'd encourage anyone interested in building secure authentication systems to read up.

### Relevant docs
More on choosing a signing algorithm
https://auth0.com/blog/rs256-vs-hs256-whats-the-difference/#RS256-or-HS256--Which-Should-You-Use-

Docs on RS256 verification
https://auth0.com/docs/secure/tokens/json-web-tokens/validate-json-web-tokens#verify-rs256-signed-tokens

**Comment by StefanPrintezis** [comment]
#3 I've created a PR to clarify env usage in the Auth0 Vapor readme example
